//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class aplicaAntimicrobianoGermen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aplicaAntimicrobianoGermen()
        {
            this.aplicaAntimicrobianoSeguim = new HashSet<aplicaAntimicrobianoSeguim>();
        }
    
        public int id { get; set; }
        public int idAplicaAntimicrobiano { get; set; }
        public string idPaciente { get; set; }
        public int numCaso { get; set; }
        public short idGermen { get; set; }
        public short idAntimicrobiano { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public short diasTratamiento { get; set; }
        public short dosisMg { get; set; }
        public short frecuencia { get; set; }
        public short idPeriodo { get; set; }
        public short idVia { get; set; }
        public short idEstadoAplicaAntimicrobiano { get; set; }
        public Nullable<short> idMotivoSuspension { get; set; }
        public Nullable<System.DateTime> fechaSuspension { get; set; }
        public bool activo { get; set; }
        public string idUsuarioIn { get; set; }
        public System.DateTime fechaHoraIn { get; set; }
    
        public virtual antimicrobiano antimicrobiano { get; set; }
        public virtual aplicaAntimicrobiano aplicaAntimicrobiano { get; set; }
        public virtual estadoAplicaAntimicrobiano estadoAplicaAntimicrobiano { get; set; }
        public virtual germen germen { get; set; }
        public virtual motivoSuspension motivoSuspension { get; set; }
        public virtual periodo periodo { get; set; }
        public virtual via via { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aplicaAntimicrobianoSeguim> aplicaAntimicrobianoSeguim { get; set; }
    }
}
