//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class aplicaAntimicrobianoSeguim
    {
        public int id { get; set; }
        public int idAplicaAntimicrobianoGermen { get; set; }
        public int idAplicaAntimicrobiano { get; set; }
        public string idPaciente { get; set; }
        public int numCaso { get; set; }
        public System.DateTime fechaHora { get; set; }
        public short idEstadoPaciente { get; set; }
        public string observacion { get; set; }
        public string cobertura { get; set; }
        public string historiaClinica { get; set; }
        public string cultivos { get; set; }
        public string recomendaciones { get; set; }
        public string respuesta { get; set; }
        public bool recibido { get; set; }
        public bool activo { get; set; }
        public string idUsuarioIn { get; set; }
        public System.DateTime fechaHoraIn { get; set; }
    
        public virtual aplicaAntimicrobianoGermen aplicaAntimicrobianoGermen { get; set; }
        public virtual estadoPaciente estadoPaciente { get; set; }
    }
}
