//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class estanciaPaciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estanciaPaciente()
        {
            this.aplicaAntimicrobiano = new HashSet<aplicaAntimicrobiano>();
        }
    
        public string idPaciente { get; set; }
        public int numCaso { get; set; }
        public string codCentroMedico { get; set; }
        public bool esCasoArca { get; set; }
        public string cod4DIngreso { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaEgreso { get; set; }
        public string codServicioInicial { get; set; }
        public string codEspecialidadInicial { get; set; }
        public bool activo { get; set; }
        public string idUsuarioIn { get; set; }
        public System.DateTime fechaHoraIn { get; set; }
    
        public virtual paciente paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aplicaAntimicrobiano> aplicaAntimicrobiano { get; set; }
    }
}
