//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paciente()
        {
            this.telefonoPaciente = new HashSet<telefonoPaciente>();
            this.estanciaPaciente = new HashSet<estanciaPaciente>();
        }
    
        public string idPaciente { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public System.DateTime fechaNacim { get; set; }
        public string sexo { get; set; }
        public string idMadre { get; set; }
        public string nombreMadre { get; set; }
        public string apellido1Madre { get; set; }
        public string apellido2Madre { get; set; }
        public string idPadre { get; set; }
        public string nombrePadre { get; set; }
        public string apellido1Padre { get; set; }
        public string apellido2Padre { get; set; }
        public bool activo { get; set; }
        public string idUsuarioIn { get; set; }
        public System.DateTime fechaHoraIn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<telefonoPaciente> telefonoPaciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estanciaPaciente> estanciaPaciente { get; set; }
    }
}
