//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Proa_Entities : DbContext
    {
        public Proa_Entities()
            : base("name=Proa_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<telefonoPaciente> telefonoPaciente { get; set; }
        public virtual DbSet<tipoTelefono> tipoTelefono { get; set; }
    
        public virtual ObjectResult<sp_BuscarPacienteProa_Result> sp_BuscarPacienteProa(string id, string nombre, string apel1, string apel2)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apel1Parameter = apel1 != null ?
                new ObjectParameter("apel1", apel1) :
                new ObjectParameter("apel1", typeof(string));
    
            var apel2Parameter = apel2 != null ?
                new ObjectParameter("apel2", apel2) :
                new ObjectParameter("apel2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarPacienteProa_Result>("sp_BuscarPacienteProa", idParameter, nombreParameter, apel1Parameter, apel2Parameter);
        }
    
        public virtual ObjectResult<sp_BuscarPacienteARCAMEDISYS_Result> sp_BuscarPacienteARCAMEDISYS(string id, string nombre, string apel1, string apel2)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apel1Parameter = apel1 != null ?
                new ObjectParameter("apel1", apel1) :
                new ObjectParameter("apel1", typeof(string));
    
            var apel2Parameter = apel2 != null ?
                new ObjectParameter("apel2", apel2) :
                new ObjectParameter("apel2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarPacienteARCAMEDISYS_Result>("sp_BuscarPacienteARCAMEDISYS", idParameter, nombreParameter, apel1Parameter, apel2Parameter);
        }
    }
}
