//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefonoPaciente
    {
        public int id { get; set; }
        public string idPaciente { get; set; }
        public short idTipoTelefono { get; set; }
        public string numero { get; set; }
        public bool activo { get; set; }
        public string idUsuarioIn { get; set; }
        public System.DateTime fechaHoraIn { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual tipoTelefono tipoTelefono { get; set; }
    }
}
