//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefonoPaciente
    {
        public int id { get; set; }
        public string idPaciente { get; set; }
        public short idTipoTelefono { get; set; }
        public string numero { get; set; }
        public bool activo { get; set; }
        public string idUsuarioIn { get; set; }
        public System.DateTime fechaHoraIn { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual tipoTelefono tipoTelefono { get; set; }
    }
}
