//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoTelefono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipoTelefono()
        {
            this.telefonoPaciente = new HashSet<telefonoPaciente>();
        }
    
        public short id { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
        public bool esCasa { get; set; }
        public bool esTrabajo { get; set; }
        public bool esCelular { get; set; }
        public bool esUrgencia { get; set; }
        public string idUsuarioIn { get; set; }
        public System.DateTime fechaHoraIn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<telefonoPaciente> telefonoPaciente { get; set; }
    }
}
