//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Estancia
    {
        public int CASO { get; set; }
        public string COD_CENTRO_MEDICO { get; set; }
        public string IDENTIFICACION { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public string COD_SERVICIO_INGRESO { get; set; }
        public string COD_SERVICIO_ACTUAL { get; set; }
        public Nullable<System.DateTime> FECHA_EGRESO { get; set; }
        public string COD_SERVICIO_EGRESO { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string NOMBRE { get; set; }
        public string SERVICIO_INGRESO { get; set; }
        public string SERVICIO_ACTUAL { get; set; }
        public string SERVICIO_INGRESO_PADRE { get; set; }
        public string SERVICIO_ACTUAL_PADRE { get; set; }
        public string COD_SERVICIO_INGRESO_PADRE { get; set; }
        public string COD_SERVICIO_ACTUAL_PADRE { get; set; }
    }
}
