//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proa_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SERVICIOS_POR_CENTRO
    {
        public string COD_CENTRO_MEDICO { get; set; }
        public string COD_SERVICIO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> AREA { get; set; }
        public string COD_SERVICIO_PADRE { get; set; }
        public string Expr1 { get; set; }
    }
}
